name: CI

on:
  push:
    branches:
      - main
      - master
      - '**/practice-problems'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install mypy flake8

    - name: Run tests
      run: |
        source venv/bin/activate
        python -m unittest discover -s tests

    - name: Run flake8
      run: |
        source venv/bin/activate
        flake8 pycanvas tests

    - name: Run mypy
      run: |
        source venv/bin/activate
        mypy pycanvas
